name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      run: git clone https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} . && git checkout ${{ github.event.after }}

    - name: Install PNPM
      run: wget --quiet -O /usr/local/bin/pnpm https://github.com/pnpm/pnpm/releases/download/v9.12.3/pnpm-linux-x64 && chmod +x /usr/local/bin/pnpm

    - run: pnpm install
    - run: pnpm build
    
    - name: Upload artifcats
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
    
    - name: Deploy
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        curl --request PATCH --header "Authorization: $DEPLOY_TOKEN" https://sillystring.party/redeploy?artifact_id=${{steps.upload.outputs.artifact-id}}
